FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-release

ARG VERSION="2021.0.0.0"
WORKDIR /srv/hermes.api
COPY . .
RUN dotnet publish src/Presentation/Presentation.csproj -c Release -o bin /p:Version=$VERSION

FROM mcr.microsoft.com/dotnet/core/aspnet:5.0
WORKDIR /src/hermes.api
COPY --from=build-release /src/hermes.api/bin .
ENTRYPOINT ["dotnet", "Presentation.dll"]
