FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-release

ARG VERSION="2021.0.0.0"
WORKDIR /srv/Hermes.Api
COPY . .
RUN dotnet publish src/Presentation/Presentation.csproj -c Release -o bin /p:Version=$VERSION

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /src/Presentation
COPY --from=build-release /src/Presentation/bin .
ENTRYPOINT ["dotnet", "Presentation.dll"]
