namespace Business.Detection.Fetching.Commands
{
    using System.Diagnostics.CodeAnalysis;
    using Style;

    [SuppressMessage(Category.Default, Check.CA1052, Justification = Reason.Autogenerated)]
    public class Nothing
    {
        public static Nothing Default => new ();
    }
}
