namespace Data.Migrations
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using Microsoft.EntityFrameworkCore.Migrations;
    using MySql.EntityFrameworkCore.Metadata;
    using Style;

    [SuppressMessage(Category.Default, Check.SA1118, Justification = Reason.Autogenerated)]
    [SuppressMessage(Category.Default, Check.CA1814, Justification = Reason.Autogenerated)]

    public partial class InsertData : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "Detections",
                columns: new[] { "Id", "Class", "Score", "Timestamp" },
                values: new object[,]
                {
                    { 1, "pet", 1, new DateTime(2021, 7, 9, 11, 36, 1, 502, DateTimeKind.Utc).AddTicks(6134) },
                    { 2, "pet", 5, new DateTime(2021, 7, 9, 11, 36, 1, 502, DateTimeKind.Utc).AddTicks(6477) },
                    { 3, "pet", 8, new DateTime(2021, 7, 9, 11, 36, 1, 502, DateTimeKind.Utc).AddTicks(6478) },
                    { 4, "pet", 4, new DateTime(2021, 7, 9, 11, 36, 1, 502, DateTimeKind.Utc).AddTicks(6479) },
                    { 5, "pet", 3, new DateTime(2021, 7, 9, 11, 36, 1, 502, DateTimeKind.Utc).AddTicks(6480) },
                    { 6, "pet", 9, new DateTime(2021, 7, 9, 11, 36, 1, 502, DateTimeKind.Utc).AddTicks(6481) },
                    { 7, "pet", 1, new DateTime(2021, 7, 9, 11, 36, 1, 502, DateTimeKind.Utc).AddTicks(6481) },
                    { 8, "pet", 1, new DateTime(2021, 7, 9, 11, 36, 1, 502, DateTimeKind.Utc).AddTicks(6482) },
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "Detections",
                keyColumn: "Id",
                keyValue: 1);

            migrationBuilder.DeleteData(
                table: "Detections",
                keyColumn: "Id",
                keyValue: 2);

            migrationBuilder.DeleteData(
                table: "Detections",
                keyColumn: "Id",
                keyValue: 3);

            migrationBuilder.DeleteData(
                table: "Detections",
                keyColumn: "Id",
                keyValue: 4);

            migrationBuilder.DeleteData(
                table: "Detections",
                keyColumn: "Id",
                keyValue: 5);

            migrationBuilder.DeleteData(
                table: "Detections",
                keyColumn: "Id",
                keyValue: 6);

            migrationBuilder.DeleteData(
                table: "Detections",
                keyColumn: "Id",
                keyValue: 7);

            migrationBuilder.DeleteData(
                table: "Detections",
                keyColumn: "Id",
                keyValue: 8);
        }
    }
}
