// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210709113601_InsertData")]
    partial class InsertData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Data.EDetection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Detections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Class = "pet",
                            Score = 1,
                            Timestamp = new DateTime(2021, 7, 9, 11, 36, 1, 502, DateTimeKind.Utc).AddTicks(6134)
                        },
                        new
                        {
                            Id = 2,
                            Class = "pet",
                            Score = 5,
                            Timestamp = new DateTime(2021, 7, 9, 11, 36, 1, 502, DateTimeKind.Utc).AddTicks(6477)
                        },
                        new
                        {
                            Id = 3,
                            Class = "pet",
                            Score = 8,
                            Timestamp = new DateTime(2021, 7, 9, 11, 36, 1, 502, DateTimeKind.Utc).AddTicks(6478)
                        },
                        new
                        {
                            Id = 4,
                            Class = "pet",
                            Score = 4,
                            Timestamp = new DateTime(2021, 7, 9, 11, 36, 1, 502, DateTimeKind.Utc).AddTicks(6479)
                        },
                        new
                        {
                            Id = 5,
                            Class = "pet",
                            Score = 3,
                            Timestamp = new DateTime(2021, 7, 9, 11, 36, 1, 502, DateTimeKind.Utc).AddTicks(6480)
                        },
                        new
                        {
                            Id = 6,
                            Class = "pet",
                            Score = 9,
                            Timestamp = new DateTime(2021, 7, 9, 11, 36, 1, 502, DateTimeKind.Utc).AddTicks(6481)
                        },
                        new
                        {
                            Id = 7,
                            Class = "pet",
                            Score = 1,
                            Timestamp = new DateTime(2021, 7, 9, 11, 36, 1, 502, DateTimeKind.Utc).AddTicks(6481)
                        },
                        new
                        {
                            Id = 8,
                            Class = "pet",
                            Score = 1,
                            Timestamp = new DateTime(2021, 7, 9, 11, 36, 1, 502, DateTimeKind.Utc).AddTicks(6482)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
