namespace Data.Migrations
{
    using System.Diagnostics.CodeAnalysis;
    using Microsoft.EntityFrameworkCore.Migrations;
    using Style;

    [SuppressMessage(Category.Default, Check.CA1707, Justification = Reason.Autogenerated)]
    public partial class Alter_Detections : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Name",
                table: "Detections");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Name",
                table: "Detections",
                type: "text",
                nullable: true);
        }
    }
}
