namespace Style
{
    public static class Reason
    {
        public const string Autogenerated = "Rule violation due to autogeneration purposes.";
        public const string Reflection = "Rule violation due to reflection purposees.";
        public const string Readability = "Rule violation due to readability purposes.";
    }
}
